# Generated by Django 2.0.4 on 2018-04-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('mass', models.IntegerField(blank=True, null=True)),
                ('hair_color', models.CharField(blank=True, choices=[('blond', 'Blond'), ('black', 'Black'), ('brown', 'Brown'), ('red', 'Red')], max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('diameter', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Planet'),
        ),
    ]
